channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=23.1.2
- pip:
  - mlflow==2.13.1
  - accelerate==0.30.1
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - gmpy2==2.1.5
  - matplotlib==3.9.0
  - numpy==1.25.1
  - packaging==23.1
  - pandas==2.0.3
  - protobuf==4.24.0
  - pyyaml==6.0
  - requests==2.31.0
  - torch==2.1.2
  - transformers==4.41.2
name: mlflow-env
