---
title: "Learning about consumer preferences for media through Generative AI"
author: "Bas Donkers, Dennis Fok, and Finn-Ole Höner"
format: 
    beamer: default
    revealjs: default
    pptx:
        reference-doc: template.pptx
        slide-level: 1
        
aspectratio: 169
---

# The marketing problem

Serving media that resonates with people through advertising, branding, or in social media posts.

Our running example here are slogans, but these could be other types of media as well.

For this, we need to learn different consumers' preferences for these slogans

When we try to learn about product preferences, there are some aspects which marketers can easily tweak, e.g. the price, brand, or quantity of a product.

For media or brand elements, this is more difficult, as it is often unclear how we can alter e.g. a slogan to make it more appealing to a specific consumer.

Currently, marketers either rely on theoretical motivations, e.g. heuristics of a "brand personality", or they can perform a conjoint analysis on a set of specific material to learn about consumers' preferences for these slogans.
 
# Shortcoming of the current methods

Heuristic approaches are highly subjective. One drawback of this is, that the company strongly depends on its marketer. If the marketer leaves, the company loses its expertise. Heuristics can also be difficult to scale up.

Choice-study based approaches are more objective and better replicable. However, in the case of media, they are limited to the material that is part of the study and it is unclear how these findings generalize. Essentially, each variation in a campaign requires a new study. And what if the ideal slogan is not part of the study set?

## Idea: Can we learn about *how* to create these slogans instead?

This would allow us to create new slogans, where we already have an idea on which consumers might like it.

Our idea is, to get a Large Language Model to re-create a specific Slogan on which we already know the consumer's preferences. We are trying to "reverse-engineer" what creates a slogan that is appealing to a specific consumer.

# What this brings to SKIM

Currently, SKIM offers different forms of Conjoint Analysis, e.g. Choice-Based, Menu-Based, or Adaptive Choice-Based Conjoint Analysis. All of these can provide insights on consumers' preferences for a specific slogan, but they provide little help in creating new, "good", slogans.

This could be a first-step towards a new form of consumer preference studies, that directly helps you to create new taglines for your customers, or to transfer learnings from one brand to another.

## What we ask from you

For a test-run on whether this idea works, we would need a dataset which contains a choice based conjoint analysis on (short) text-media, e.g. slogans, taglines, or tweets. This would allow us to learn about a relationship between consumer's preferences and the "generation space" of these text-media.

<!-- 
# Generative AI and Preferences

- Generative personalization based on consumer-preferences
- Provide a continuous representation of consumer preferences, that allows e.g. personalized communication
- Performing a conjoint study on slogans, and mapping these slogans into a representation that an LLM can use to generate new slogans in accordance with consumers preferences
- Deterministic summary for a given text based on an LLM

*First progress on this idea, working on summary embedding for LLMs in MPhil*

Can make these space's dimensions "interpretable", about established branding concepts [@sisodiaAutomaticallyDiscoveringVisual2022]

Maybe, this "reverse engineering" of a generative model yields interesting insights in other fields as well. E.g. in ideation, maybe we can use these "deterministic" summaries to identify new ideas or to validate ideas.
 -->
