channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=24.0
- pip:
  - mlflow==2.13.0
  - cloudpickle==3.0.0
  - dill==0.3.6
  - numpy==1.26.2
  - packaging==23.1
  - pandas==2.1.4
  - pyyaml==6.0.1
  - torch==2.3.0
  - tqdm==4.65.0
name: mlflow-env
